[env:EBYTE_ESP32-S3]
extends = esp32s3_base
; board assumes the lowest spec WROOM module: 4 MB (Quad SPI) Flash, No PSRAM
board = esp32-s3-devkitc-1

board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
    
board_level = extra
build_flags =
  ${esp32s3_base.build_flags}
  -D EBYTE_ESP32_S3
  -I variants/esp32s3/EBYTE_ESP32-S3
  -D BOARD_HAS_PSRAM
  -D CONFIG_BT_BLE_ENABLED=1
  -D CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST=1
  -D CONFIG_SPIRAM_CACHE_WORKAROUND=1
